#!/usr/bin/env python3
"""Inject MAKE_PLANS + INSTRUCTIONS for the 6 new couple-food ideas (2026-09-28).
IDEAS entries were already added (ranks 139-144). Anchors follow the
inject-5-thincell.py convention (explicit section markers)."""
import os, re, shutil

ROOT = os.path.expanduser("~/workspace/builds/pick-my-costume")
SRC = os.path.join(ROOT, "index.html")
BAK = "/tmp/index.html.pre-6foodplans.bak"

NEW_IDS = ["milk-cookies", "chips-guac", "sushi-soy", "burger-fries", "donut-coffee", "wine-cheese"]

PLANS = '''  "milk-cookies": {buy: ["White t-shirt or tunic", "Brown t-shirt or tunic", "White and brown craft felt", "Black marker", "Fabric glue or safety pins"], cost: "~$8", time: "~25 min", steps: ["Decide who is milk and who is the cookie before cutting anything.", "Milk: cut a white felt carton front, write MILK on it in block letters, and pin it to the white tunic.", "Cookie: pin a big brown felt circle to the brown tunic and glue on felt chips.", "Wear the tunics over regular clothes and pose side by side."]},
  "chips-guac": {buy: ["Green t-shirt or tunic", "Tan t-shirt or tunic", "Red, yellow, and tan felt", "Headband", "Fabric glue"], cost: "~$8", time: "~30 min", steps: ["Guac: glue red and yellow felt dots onto the green tunic.", "Chip: cut a giant tan felt triangle and glue it upright to the headband.", "Let the glue dry flat for 20 minutes before wearing.", "Pose with the guac serving the chip from a bowl."]},
  "sushi-soy": {buy: ["White t-shirt", "Dark t-shirt", "Orange and black felt", "Cardboard and dark brown paint", "Red paper for cap"], cost: "~$8", time: "~30 min", steps: ["Sushi: glue an orange felt salmon rectangle on the white tunic with a black seaweed waistband.", "Soy sauce: cut, paint, and wear a tall cardboard bottle like a sandwich board.", "Fold a red paper cap for the bottle top.", "The sushi dips toward the soy bottle in every photo."]},
  "burger-fries": {buy: ["Tan t-shirt", "Red t-shirt", "Green, red, yellow, and tan felt", "Paper bowl", "Cardboard, red paint, yellow paper"], cost: "~$10", time: "~35 min", steps: ["Burger: glue felt lettuce, tomato, and cheese layers on the tan tunic and wear the felt-covered bowl upside down as the bun.", "Fries: build a red cardboard carton with yellow paper fry sticks poking out.", "Wear the carton like a sandwich board over the red t-shirt.", "Line the carton with a plastic bag and fill it with wrapped candy."]},
  "donut-coffee": {buy: ["White and brown t-shirts", "Pink and tan felt", "Cardboard for ring and cup", "Brown paint", "White paper for lid"], cost: "~$10", time: "~35 min", steps: ["Donut: cover a big cardboard ring with tan fabric, add a pink felt frosting ring with sprinkles, and wear it like a sandwich board.", "Coffee: roll and paint a tall cardboard cup, add a white paper lid.", "Wear the cup over the brown t-shirt.", "Link arms for the full breakfast-date effect."]},
  "wine-cheese": {buy: ["Burgundy t-shirt", "Yellow t-shirt", "White and burgundy felt", "Fabric glue"], cost: "~$8", time: "~25 min", steps: ["Wine: glue a white felt wine glass with burgundy wine onto the burgundy tunic.", "Cheese: cut round holes in a yellow felt triangle and pin it over the yellow tunic.", "Raise your glasses together for every photo."]},'''

INSTR = '''  "milk-cookies":{"m":["White t-shirt or tunic, 1 (own, or buy: thrift store)","Brown t-shirt or tunic, 1 (own, or buy: thrift store)","White craft felt, 1 sheet 9x12 inches (buy: craft store)","Brown craft felt, 2 sheets 9x12 inches (buy: craft store)","Black marker, 1 (own)","Fabric glue, 1 bottle (buy: craft store)","Safety pins, 4 (buy: dollar store, or raid the sewing kit)","Scissors, 1 pair"],"s":["Buy the felt, marker, and glue. Pull a white and a brown t-shirt from the closet.","Milk: cut the white felt into a carton-front rectangle about the size of a placemat. Write MILK across it in big block letters with the black marker.","Pin the carton front to the white t-shirt, pinning from inside the shirt so the pin backs face the fabric and never the skin.","Cookie: cut the biggest circle you can from the brown felt and pin it centered on the brown t-shirt.","Cut a dozen small chip shapes from the leftover brown felt and glue them onto the cookie circle. Uneven spacing looks more like a real cookie.","Safety: check every pin from the inside before heading out, and keep glued felt flat so edges do not curl and catch.","Optional pro finish: the milk person carries a paper straw. One shared prop is what makes a pair read as a pair."],"time":"25 min","cost":"$3-8","effort":"Easy","faqs":[["How do you keep the felt pieces from flopping?","Pin each felt piece at 4 points, not 2. Felt pinned at the corners stays flat all night, and fabric glue on the chips keeps them from peeling."],["What if we have no brown felt?","A brown paper grocery bag cut into a circle works for one night. Glue paper chips on and pin the circle to the shirt."]]},
  "chips-guac":{"m":["Green t-shirt or tunic, 1 (own, or buy: thrift store)","Tan t-shirt or tunic, 1 (own, or buy: thrift store)","Red craft felt, 1 sheet 9x12 inches (buy: craft store)","Yellow craft felt, 1 sheet 9x12 inches (buy: craft store)","Tan craft felt, 2 sheets 9x12 inches (buy: craft store)","Headband, 1 (buy: dollar store, or use your own)","Fabric glue, 1 bottle (buy: craft store)","Scissors, 1 pair"],"s":["Buy the felt and glue. Pull a green and a tan t-shirt from the closet.","Guac: cut small circles from the red and yellow felt, about quarter size. These are the tomato and onion.","Glue the dots scattered across the front of the green t-shirt. Let the glue dry flat for 20 minutes.","Chip: cut a triangle from the tan felt about 2 feet tall with a wide base.","Glue the base of the triangle to the headband so it stands upright. Add a second small triangle behind it for stiffness.","Safety: keep the chip triangle light, felt only, so it cannot poke anyone in a crowd. Skip cardboard for the tall piece.","Optional pro finish: the guac person carries a small bowl. Serving the chip person from it in photos is the whole joke."],"time":"30 min","cost":"$3-8","effort":"Easy","faqs":[["How do you keep the chip triangle standing up?","Two layers of felt glued together hold their shape. For a taller chip, glue a pipe cleaner up the center as a spine."],["Will the felt dots survive the night?","Fabric glue on clean, dry cotton holds for an evening. Press each dot flat for 30 seconds when you glue it."]]},
  "sushi-soy":{"m":["White t-shirt or tunic, 1 (own, or buy: thrift store)","Dark brown or black t-shirt, 1 (own, or buy: thrift store)","Orange craft felt, 1 sheet 9x12 inches (buy: craft store)","Black craft felt, 1 sheet 9x12 inches (buy: craft store)","Cardboard for the soy bottle, 1 sheet (make: from a shipping box)","Dark brown acrylic paint, 1 bottle (buy: craft store)","Red paper for the bottle cap, 1 sheet (buy: dollar store)","Ribbon for straps, about 2 yards (buy: craft store)","Tape, 1 roll","Scissors, 1 pair"],"s":["Buy the felt, paint, and ribbon. Pull a white and a dark t-shirt from the closet.","Sushi: cut an orange felt rectangle about the size of a paperback and glue it across the chest of the white t-shirt. This is the salmon.","Cut a black felt band 3 inches wide and glue it around the waist over the orange rectangle, like the seaweed holding the fish on.","Soy sauce: cut a tall bottle shape from the cardboard, about 2 feet tall, with a narrow neck.","Paint the bottle dark brown and let it dry flat. Fold red paper into a cap and tape it to the neck.","Tape ribbon loops to the top of the bottle and wear it like a sandwich board over the dark t-shirt.","Safety: round all cardboard corners with the scissors so nobody gets poked in a crowd.","Optional pro finish: the sushi person leans toward the soy bottle in every photo. The dip is the pose."],"time":"30 min","cost":"$3-8","effort":"Easy","faqs":[["How do you keep the cardboard bottle from folding?","Use double-wall cardboard from a shipping box, not a cereal box, and keep the bottle under 2 feet tall."],["What if the paint is still tacky at party time?","Paint the bottle first and let it dry while you build the sushi. Dark paint needs a full hour on cardboard."]]},
  "burger-fries":{"m":["Tan t-shirt, 1 (own, or buy: thrift store)","Red t-shirt, 1 (own, or buy: thrift store)","Green, red, and yellow craft felt, 1 sheet each 9x12 inches (buy: craft store)","Tan felt for the bun top, 1 sheet (buy: craft store)","Paper bowl for the bun, 1 large (buy: grocery store)","Cardboard for the fry carton, 1 sheet (make: from a shipping box)","Red acrylic paint or red paper, 1 (buy: craft store)","Yellow paper for fry sticks (buy: dollar store, or make: from paper)","Tape, 1 roll","Scissors, 1 pair"],"s":["Buy the felt, bowl, and paint. Pull a tan and a red t-shirt from the closet.","Burger: cut wavy felt strips, green for lettuce, red for tomato, yellow for cheese. Glue them in a stack across the tan t-shirt.","Cover the paper bowl with tan felt and wear it upside down as the bun top.","Fries: fold the cardboard into an open-top carton and paint it red, or cover it with red paper. Let it dry.","Cut yellow paper into fry sticks and glue them poking out of the carton top.","Wear the fry carton like a sandwich board over the red t-shirt, with ribbon straps over the shoulders.","Safety: round the cardboard corners, and keep the fry sticks soft paper, never wood, so the carton is crowd-safe.","Optional pro finish: drop real wrapped candy into the fry carton. A fry box that hands out candy wins every party."],"time":"35 min","cost":"$5-10","effort":"Easy","faqs":[["How do you keep the bun bowl on your head?","Wear it tilted back like a hat, not balanced on top. A strip of double-sided tape inside the rim keeps it put."],["Can the fry carton hold real candy?","Yes, line it with a plastic bag first so grease never touches the cardboard, and keep it to wrapped candy."]]},
  "donut-coffee":{"m":["White t-shirt, 1 (own, or buy: thrift store)","Brown t-shirt, 1 (own, or buy: thrift store)","Pink craft felt, 2 sheets 9x12 inches (buy: craft store)","Cardboard ring for the donut, 1 large (make: from a shipping box)","Tan fabric or paper to cover the ring (own, or buy: craft store)","Cardboard for the coffee cup, 1 sheet (make: from a shipping box)","Brown acrylic paint, 1 bottle (buy: craft store)","White paper for the cup lid, 1 sheet (buy: dollar store)","Tape, 1 roll","Scissors, 1 pair","Ribbon for straps, about 2 yards (buy: craft store)"],"s":["Buy the felt and paint. Pull a white and a brown t-shirt from the closet.","Donut: cut a large ring from the cardboard, about 2 feet across, with a 10-inch hole in the middle.","Cover the ring with tan fabric or paper, then glue a pink felt ring on top for the frosting. Dot it with small felt sprinkles in bright colors.","Tape ribbon loops to the ring and wear it over the white t-shirt like a sandwich board.","Coffee: roll cardboard into a tall cup shape and tape the seam. Paint it brown and let it dry.","Fold the white paper into a lid and tape it to the top of the cup. Wear the cup like a sandwich board over the brown t-shirt.","Safety: round all cardboard edges, and keep the donut hole big enough that arms move freely.","Optional pro finish: the coffee person links arms with the donut person. The breakfast-date pose photographs itself."],"time":"35 min","cost":"$5-10","effort":"Easy","faqs":[["How do you cut a clean donut ring?","Trace a large mixing bowl for the outside and a salad plate for the hole. Cut the hole first while the cardboard is whole, then the outside."],["How do you keep the frosting ring from peeling?","Glue the pink felt in sections and press each for 30 seconds. Felt glued all at once bubbles and lifts."]]},
  "wine-cheese":{"m":["Burgundy or maroon t-shirt, 1 (own, or buy: thrift store)","Yellow t-shirt, 1 (own, or buy: thrift store)","White craft felt, 1 sheet 9x12 inches (buy: craft store)","Burgundy craft felt, 1 sheet 9x12 inches (buy: craft store)","Fabric glue, 1 bottle (buy: craft store)","Scissors, 1 pair"],"s":["Buy the felt and glue. Pull a burgundy and a yellow t-shirt from the closet.","Wine: cut a wine glass shape from the white felt, bowl, stem, and base in one piece, about a foot tall.","Cut a smaller burgundy felt shape for the wine inside the glass and glue it onto the white glass.","Glue the finished glass centered on the burgundy t-shirt.","Cheese: cut round holes from a yellow felt triangle and pin it over the yellow t-shirt. Swiss reads instantly.","Safety: if cutting holes in the shirt itself, keep them small and away from the seams so the shirt holds its shape.","Optional pro finish: raise your glasses together for every photo. The toast is the costume, so commit to it."],"time":"25 min","cost":"$3-8","effort":"Easy","faqs":[["How do you cut clean holes in the cheese?","Fold the felt and cut half-circles along the fold, then unfold for perfect circles. Small scissors beat big ones for the curves."],["What if we cannot find a burgundy shirt?","A dark red shirt works. The wine glass felt carries the costume either way."]]}'''


def main():
    src = open(SRC, encoding="utf-8").read()
    for nid in NEW_IDS:
        assert src.count('{id:"%s"' % nid) == 1, "IDEAS entry missing/dup: " + nid
        assert '"%s": {buy:' % nid not in src, "MAKE_PLANS already has " + nid
        assert '"%s":{"m"' % nid not in src, "INSTRUCTIONS already has " + nid
    shutil.copy2(SRC, BAK)

    # 1. MAKE_PLANS: block ends with }; immediately before the CONFIG: SHARE comment.
    share_marker = "/* ================= CONFIG: SHARE"
    sh_i = src.index(share_marker)
    prev = src[:sh_i].rstrip()
    assert prev.endswith("};"), "unexpected MAKE_PLANS tail: " + prev[-40:]
    prev = prev[:-2].rstrip()
    assert prev.endswith(","), "MAKE_PLANS tail entry has no comma"
    src = prev + "\n" + PLANS + "\n};" + src[sh_i:]

    # 2. INSTRUCTIONS: map ends with }; immediately before the MAKE PLANS marker.
    mk_marker = "/* ================= MAKE PLANS"
    mk_i = src.index(mk_marker)
    prev = src[:mk_i].rstrip()
    assert prev.endswith("};"), "unexpected INSTRUCTIONS tail: " + prev[-40:]
    prev = prev[:-2].rstrip()  # drop the }; object close
    if prev.endswith("},"):
        prev = prev[:-1]  # drop trailing comma; last entry now ends }
    assert prev.endswith("}"), "INSTRUCTIONS tail not an object close: " + prev[-60:]
    src = prev + ",\n" + INSTR + "\n};" + src[mk_i:]

    open(SRC, "w", encoding="utf-8").write(src)

    # ---- content-placement verification (assert CONTENT, not just counts) ----
    t = open(SRC, encoding="utf-8").read()
    ideas_scope = t[t.index("var IDEAS = ["):t.index("var INSTRUCTIONS = {")]
    in_scope = t[t.index("var INSTRUCTIONS = {"):t.index("/* ================= MAKE PLANS")]
    mp_scope = t[t.index("var MAKE_PLANS = {"):t.index("/* ================= CONFIG: SHARE")]
    for nid in NEW_IDS:
        assert ('{id:"%s"' % nid) in ideas_scope, nid + " missing from IDEAS"
        assert ('"%s":{"m"' % nid) in in_scope, nid + " missing/misplaced in INSTRUCTIONS"
        assert ('"%s": {buy:' % nid) in mp_scope, nid + " missing/misplaced in MAKE_PLANS"
        assert ('"%s":{"m"' % nid) not in mp_scope, nid + " INSTRUCTIONS leaked into MAKE_PLANS"
    # spot-check content landed intact
    assert '"milk-cookies":{"m":["White t-shirt or tunic, 1' in in_scope
    assert '"wine-cheese": {buy: ["Burgundy t-shirt"' in mp_scope
    print("injected MAKE_PLANS + INSTRUCTIONS for 6 ideas; placement verified")


if __name__ == "__main__":
    main()
